name: Test CI

on:
  push:
    branches: [ "ci-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - name: Build
      run: echo $TERM
